name: Test C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt install g++ cmake
      - name: compile
        run: |
          cmake src
          make
      - name: test
        run: ctest --verbose
