name: Test C++

on:
  push:
    branches:
      - main
  pull_request:
    branches: -main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt install g++
      - name: compile
        run: g++ src/main.cpp
      - name: test
        run: ./a.out 10 31
